version: "3.9"

services:
  userbot:
    build: .
    container_name: tg_userbot
    restart: always
    env_file: .env
    volumes:
      - ./channels.csv:/app/channels.csv
      - ./channel_vibes.json:/app/channel_vibes.json
      - ./bot.log:/app/bot.log
